import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const prod = process.argv.includes("--production");
const watch = process.argv.includes("--watch");

const banner = "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. DO NOT EDIT DIRECTLY. */";

const builtins = builtinModules.flatMap((moduleName) => [moduleName, `node:${moduleName}`]);
const obsidianRuntimeExternals = ["@codemirror/state", "@codemirror/view"];

const ctx = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", ...obsidianRuntimeExternals, ...builtins],
  format: "cjs",
  target: "es2020",
  sourcemap: prod ? false : "inline",
  minify: prod,
  outfile: "main.js",
  logLevel: "info",
});

if (watch) {
  await ctx.watch();
  console.log("Watching for changes...");
} else {
  await ctx.rebuild();
  await ctx.dispose();
}
