import fs from "node:fs";
import path from "node:path";
import manifest from "../../manifest.json";
import packageJson from "../../package.json";
import versions from "../../versions.json";
import { releaseAssetNames } from "../../scripts/release-package-policy.mjs";
import { describe, expect, it } from "vitest";

const root = path.resolve(import.meta.dirname, "../..");
const repo = "MaverickHQ/obsidian-vault-reader";

function readText(relativePath: string): string {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

describe("community plugin submission policy", () => {
  it("defines the exact Obsidian community directory submission metadata", () => {
    const submission = readText("docs/community-plugin-submission.md");

    expect(submission).toContain("# Obsidian Community Plugin Submission");
    expect(submission).toContain(`"id": "${manifest.id}"`);
    expect(submission).toContain(`"name": "${manifest.name}"`);
    expect(submission).toContain(`"author": "${manifest.author}"`);
    expect(submission).toContain(
      `"description": "${manifest.description} - This plugin has not been manually reviewed by Obsidian staff."`,
    );
    expect(submission).toContain(`"repo": "${repo}"`);
    expect(manifest.description).toContain("speed reading");
    expect(manifest.description).not.toMatch(/\bRSVP\b/i);
    expect(submission).toContain("https://community.obsidian.md");
    expect(submission).toContain(`https://github.com/${repo}`);
  });

  it("captures release tag, version, and asset requirements for Obsidian install", () => {
    const submission = readText("docs/community-plugin-submission.md");

    expect(packageJson.version).toBe(manifest.version);
    expect(versions[manifest.version as keyof typeof versions]).toBe(manifest.minAppVersion);
    expect(submission).toContain(`Release tag: ${manifest.version}`);
    expect(submission).toContain("tagged identically to the version inside `manifest.json`");
    expect(submission).toContain(`Assets: ${releaseAssetNames.join(", ")}`);
    expect(submission).toContain(
      "Artifact attestations are generated by the GitHub release workflow.",
    );
  });

  it("records that final pre-submission visibility, release QA, and GitHub safety gates are complete", () => {
    const submission = readText("docs/community-plugin-submission.md");

    expect(submission).toContain("Repository visibility is public.");
    expect(submission).toContain("Manual clean-vault Obsidian QA passed from release assets.");
    expect(submission).toContain("Branch protection is enabled on `main`.");
    expect(submission).toContain("Private vulnerability reporting is enabled.");
    expect(submission).toContain(
      "The historical `obsidianmd/obsidian-releases` PR path is no longer available.",
    );
    expect(submission).toContain(
      "BRAT/public beta is optional and deferred unless manual QA finds risk.",
    );
  });
});
